const appName = "Trivia Showdown";

export const copy = {
  appName,
  common: {
    saving: "Saving…",
    delete: "Delete",
    cancel: "Cancel",
  },
  welcome: {
    badge: "10 questions · multiple choice",
    titlePrefix: "Trivia",
    titleAccent: "Showdown",
    tagline: "Test your knowledge against the clock and your friends.",
    startButton: "Start",
    leaderboardButton: "Leaderboard",
    settingsLabel: "Settings",
    createQuestionsButton: "Create questions",
  },
  roles: {
    you: "(You)",
    admin: "ADMIN",
    member: "MEMBER",
  },
  trivia: {
    genericErrorMessage: "Something went wrong",
    retryButton: "Try again",
    questionLabel: "Question",
    ofLabel: "of",
    timeLeftSuffix: "s",
    nextButton: "Next question",
    seeResultsButton: "See results",
    timesUpMessage: "Time's up! You didn't answer in time.",
    readyHeading: "Ready?",
    readyTagline: "15 seconds per question. Let's go!",
    beginButton: "Begin",
    categoriesHeading: "Categories",
    categoriesHint: "Pick a few, or leave blank for anything.",
    noQuestionsForCategoriesMessage:
      "No questions found for the selected categories — try picking a few more.",
    questionCountLabel: "How many questions?",
    questionCountHint: "Between 1 and 50.",
    shortfallDialogTitle: "Not enough questions",
    shortfallDialogDescription:
      "This only gives {available}, which doesn't fit your request of {requested}.",
    playWithAvailableButton: "Play with {available}",
    chooseMoreCategoriesButton: "Choose more categories",
    difficultyHeading: "Difficulty",
    anyDifficultyLabel: "Any",
    modeSelectHeading: "How do you want to play?",
    modeSelectTagline: "Pick a mode to get started.",
    backToModesButton: "Back to game modes",
    quickPlayLabel: "Quick Play",
    quickPlayDescription: "Jump into a round with your own settings.",
    dailyLabel: "Daily",
    dailyDescription: "One shared round, same for everyone today.",
    dailyReadyTagline: "One shared round for everyone today — {count}.",
    weeklyLabel: "Weekly",
    weeklyDescription: "A bigger round, open all week.",
    monthlyLabel: "Monthly",
    monthlyDescription: "The championship round for the month.",
    eventLabel: "Event",
    eventDescription: "Special one-off rounds, like Friday bar trivia.",
    gameRoomLabel: "Game Room",
    gameRoomDescription: "Create or join a room to play head-to-head.",
    comingSoonBadge: "Soon",
    comingSoonHeading: "Coming soon",
    comingSoonMessage: "{mode} isn't ready yet — check back soon!",
  },
  appHeader: {
    backLabel: "Back to welcome screen",
  },
  results: {
    heading: "Round complete!",
    scoreLabel: "You scored",
    leaderboardButton: "Leaderboard",
    reactionGreat: "Nailed it! 🎉",
    reactionGood: "Nice round! 🙌",
    reactionOkay: "Not bad - buuut maybe go again? 🤔",
    reactionTryAgain: "Rough one - try again! 😅",
    shortRoundNote: "Only {total} were available for this round's settings.",
  },
  leaderboard: {
    heading: "Leaderboard",
    emptyMessage: "No scores yet — be the first to play!",
    playAgainButton: "Play again",
    playNowButton: "Play now",
    dailyViewLabel: "Daily",
    allTimeViewLabel: "All-time",
    noDailyRoundMessage: "No Daily round for this date.",
    datePickerLabel: "Date",
  },
  themeToggle: {
    ariaLabel: "Toggle color theme",
    lightLabel: "☀️ Light",
    darkLabel: "🌙 Dark",
  },
  admin: {
    manageRolesHeading: "Manage roles",
    roleSavedMessage: "Role updated",
    roleSaveErrorMessage: "Couldn't update role. Please try again.",
    manageQuestionsHeading: "Manage questions",
    questionTextLabel: "Question",
    choicesLabel: "Choices",
    choiceLabel: "Choice",
    correctAnswerLabel: "Correct answer",
    correctAnswerHint: "Select the radio button next to the correct choice.",
    categoryLabel: "Category",
    categoryPlaceholder: "Choose category",
    difficultyLabel: "Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    imageLabel: "Image (optional)",
    createQuestionButton: "Create question",
    deleteQuestionConfirmTitle: "Delete this question?",
    deleteQuestionConfirmDescription:
      "This can't be undone. The question will be permanently removed.",
    questionDeletedMessage: "Question deleted",
    questionDeleteErrorMessage: "Couldn't delete question. Please try again.",
    noQuestionsMessage: "No questions yet — create the first one above.",
    noCategoryLabel: "Other",
    noIdFound: "No user id found",
    resetPasswordButton: "Reset password",
    resetPasswordConfirmMessage:
      "This generates a new password for this user and copies it to your clipboard — share it with them directly.",
    resetPasswordSuccessMessage: "New password copied to clipboard",
    resetPasswordErrorMessage: "Couldn't reset password. Please try again.",
    deleteUserButton: "Delete user",
    deleteUserConfirmTitle: "Delete this user?",
    deleteUserConfirmDescription:
      "This can't be undone. Their scores will be removed, but any questions they created will be kept. Type their name to confirm.",
    deleteUserConfirmPlaceholder: "Type the user's name",
    userDeletedMessage: "User deleted",
    userDeleteErrorMessage: "Couldn't delete user. Please try again.",
  },
  auth: {
    signUp: {
      heading: "Sign up",
      nameLabel: "Name",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign up",
      pendingButton: "Signing up…",
      footerText: "Already have an account?",
      footerLinkLabel: "Log in",
    },
    signIn: {
      heading: "Sign in",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign in",
      pendingButton: "Signing in…",
      footerText: "Don't have an account?",
      footerLinkLabel: "Sign up",
    },
    signOutButton: "Sign out",
  },
} as const;
