const appName = "Trivia Showdown";

export const copy = {
  appName,
  common: {
    saving: "Saving…",
    delete: "Delete",
    cancel: "Cancel",
  },
  welcome: {
    badge: "10 questions · multiple choice",
    titlePrefix: "Trivia",
    titleAccent: "Showdown",
    tagline: "Test your knowledge against the clock and your friends.",
    startButton: "Start",
    leaderboardButton: "Leaderboard",
    settingsLabel: "Settings",
    createQuestionsButton: "Create questions",
  },
  roles: {
    you: "(You)",
    admin: "ADMIN",
    member: "MEMBER",
  },
  trivia: {
    genericErrorMessage: "Something went wrong",
    retryButton: "Try again",
    questionLabel: "Question",
    ofLabel: "of",
    timeLeftSuffix: "s",
    nextButton: "Next question",
    seeResultsButton: "See results",
    readyHeading: "Ready?",
    readyTagline: "10 questions, 15 seconds each. Let's go!",
    beginButton: "Begin",
    categoriesHeading: "Categories",
    categoriesHint: "Pick a few, or leave blank for anything.",
    noQuestionsForCategoriesMessage:
      "No questions found for the selected categories — try picking a few more.",
  },
  appHeader: {
    backLabel: "Back to Trivia Showdown",
  },
  results: {
    heading: "Round complete!",
    scoreLabel: "You scored",
    playAgainButton: "Play again",
    leaderboardButton: "Leaderboard",
    reactionGreat: "Nailed it! 🎉",
    reactionGood: "Nice round! 🙌",
    reactionOkay: "Not bad - buuut maybe go again? 🤔",
    reactionTryAgain: "Rough one - try again! 😅",
  },
  leaderboard: {
    heading: "Leaderboard",
    emptyMessage: "No scores yet — be the first to play!",
    scoreSavedMessage: "Saved!",
    savingButton: "Save",
    playAgainButton: "Play again",
    playNowButton: "Play now",
  },
  themeToggle: {
    ariaLabel: "Toggle color theme",
    lightLabel: "☀️ Light",
    darkLabel: "🌙 Dark",
  },
  admin: {
    manageRolesHeading: "Manage roles",
    roleSavedMessage: "Role updated",
    roleSaveErrorMessage: "Couldn't update role. Please try again.",
    manageQuestionsHeading: "Manage questions",
    questionTextLabel: "Question",
    choicesLabel: "Choices",
    choiceLabel: "Choice",
    correctAnswerLabel: "Correct answer",
    correctAnswerHint: "Select the radio button next to the correct choice.",
    categoryLabel: "Category",
    categoryPlaceholder: "Choose category",
    difficultyLabel: "Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    imageLabel: "Image (optional)",
    createQuestionButton: "Create question",
    deleteQuestionConfirmTitle: "Delete this question?",
    deleteQuestionConfirmDescription:
      "This can't be undone. The question will be permanently removed.",
    questionDeletedMessage: "Question deleted",
    questionDeleteErrorMessage: "Couldn't delete question. Please try again.",
    noQuestionsMessage: "No questions yet — create the first one above.",
    noCategoryLabel: "No category",
    noIdFound: "No user id found",
    resetPasswordButton: "Reset password",
    resetPasswordConfirmMessage:
      "This generates a new password for this user and copies it to your clipboard — share it with them directly.",
    resetPasswordSuccessMessage: "New password copied to clipboard",
    resetPasswordErrorMessage:
      "Couldn't reset password. Please try again.",
    deleteUserButton: "Delete user",
    deleteUserConfirmTitle: "Delete this user?",
    deleteUserConfirmDescription:
      "This can't be undone. Their scores will be removed, but any questions they created will be kept. Type their name to confirm.",
    deleteUserConfirmPlaceholder: "Type the user's name",
    userDeletedMessage: "User deleted",
    userDeleteErrorMessage: "Couldn't delete user. Please try again.",
  },
  auth: {
    signUp: {
      heading: "Sign up",
      nameLabel: "Name",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign up",
      pendingButton: "Signing up…",
      footerText: "Already have an account?",
      footerLinkLabel: "Log in",
    },
    signIn: {
      heading: "Sign in",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign in",
      pendingButton: "Signing in…",
      footerText: "Don't have an account?",
      footerLinkLabel: "Sign up",
    },
    signOutButton: "Sign out",
  },
} as const;
