const appName = "Trivia Showdown";

export const copy = {
  appName,
  welcome: {
    badge: "10 questions · multiple choice",
    titlePrefix: "Trivia",
    titleAccent: "Showdown",
    tagline: "Test your knowledge against the clock and your friends.",
    startButton: "Start",
    leaderboardButton: "Leaderboard",
  },
  trivia: {
    genericErrorMessage: "Something went wrong",
    retryButton: "Try again",
    questionLabel: "Question",
    ofLabel: "of",
    timeLeftSuffix: "s",
    nextButton: "Next question",
    seeResultsButton: "See results",
    readyHeading: "Ready?",
    readyTagline: "10 questions, 15 seconds each. Let's go!",
    beginButton: "Begin",
  },
  appHeader: {
    backLabel: "Back to Trivia Showdown",
  },
  results: {
    heading: "Round complete!",
    scoreLabel: "You scored",
    playAgainButton: "Play again",
    leaderboardButton: "Leaderboard",
    reactionGreat: "Nailed it! 🎉",
    reactionGood: "Nice round! 🙌",
    reactionOkay: "Not bad - buuut maybe go again? 🤔",
    reactionTryAgain: "Rough one - try again! 😅",
  },
  leaderboard: {
    heading: "Leaderboard",
    emptyMessage: "No scores yet — be the first to play!",
    scoreSavedMessage: "Saved!",
    savingButton: "Save",
    playAgainButton: "Play again",
    playNowButton: "Play now",
  },
  themeToggle: {
    ariaLabel: "Toggle color theme",
    lightLabel: "☀️ Light",
    darkLabel: "🌙 Dark",
  },
  auth: {
    signUp: {
      heading: "Sign up",
      nameLabel: "Name",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign up",
      pendingButton: "Signing up…",
      footerText: "Already have an account?",
      footerLinkLabel: "Log in",
    },
    signIn: {
      heading: "Sign in",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitButton: "Sign in",
      pendingButton: "Signing in…",
      footerText: "Don't have an account?",
      footerLinkLabel: "Sign up",
    },
    signOutButton: "Sign out",
  },
} as const;
